version: "3"
services:
  web:
    network_mode: "host"        
    restart: on-failure
  mail_bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mail_bot
    command: python main.py 