version: "3"
services:
  web:
    network_mode: "host"        
    restart: on-failure
  rest_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rest_api
    ports:
      - "80:80"

    command: python main.py 

